# Generated by Django 5.1.12 on 2025-10-27 11:13

import django.db.models.deletion
import services.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Months",
            fields=[
                ("month_id", models.AutoField(primary_key=True, serialize=False)),
                ("month_name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("main_value", models.TextField()),
                (
                    "month_image",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("status", models.BooleanField(default=True)),
                ("base_yield", models.DecimalField(decimal_places=2, max_digits=10)),
                ("ideal_temp", models.DecimalField(decimal_places=2, max_digits=5)),
                ("ideal_precip", models.IntegerField()),
                ("temperature", models.DecimalField(decimal_places=2, max_digits=5)),
                ("precipitation", models.IntegerField()),
            ],
            options={
                "db_table": "services_months",
            },
        ),
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="email адрес"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        verbose_name="Является ли пользователь менеджером?",
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False, verbose_name="Является ли пользователь админом?"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            managers=[
                ("objects", services.models.NewUserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Months_calculation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Черновик"),
                            ("deleted", "Удалён"),
                            ("submitted", "Сформирован"),
                            ("finished", "Завершён"),
                            ("rejected", "Отклонён"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "location",
                    models.CharField(
                        choices=[
                            ("moscow", "Москва"),
                            ("spb", "Санкт-Петербург"),
                            ("kazan", "Казань"),
                        ],
                        default="moscow",
                        max_length=50,
                    ),
                ),
                (
                    "person",
                    models.CharField(
                        choices=[
                            ("ivanov", "Иванов И.И."),
                            ("petrov", "Петров П.П."),
                            ("sidorov", "Сидоров С.С."),
                        ],
                        default="ivanov",
                        max_length=50,
                    ),
                ),
                (
                    "result_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "moderator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="moderated_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "services_months_calculation",
            },
        ),
        migrations.CreateModel(
            name="Month_indicators",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sum_precipitation",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("avg_temp", models.DecimalField(decimal_places=2, max_digits=5)),
                ("comment", models.TextField(blank=True, null=True)),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="services.months",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="services.months_calculation",
                    ),
                ),
            ],
            options={
                "db_table": "services_month_indicators",
                "unique_together": {("order", "service")},
            },
        ),
    ]
