# Generated by Django 5.1.12 on 2025-09-17 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="location",
            field=models.CharField(
                choices=[
                    ("moscow", "Москва"),
                    ("spb", "Санкт-Петербург"),
                    ("kazan", "Казань"),
                ],
                default="moscow",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="person",
            field=models.CharField(
                choices=[
                    ("ivanov", "Иванов И.И."),
                    ("petrov", "Петров П.П."),
                    ("sidorov", "Сидоров С.С."),
                ],
                default="ivanov",
                max_length=50,
            ),
        ),
    ]
