# Generated by Django 5.1.12 on 2025-09-30 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0002_alter_order_location_alter_order_person"),
    ]

    operations = [
        # Rename models
        migrations.RenameModel(
            old_name="Service",
            new_name="Months",
        ),
        migrations.RenameModel(
            old_name="Order",
            new_name="Months_calculation",
        ),
        migrations.RenameModel(
            old_name="OrderService",
            new_name="Month_indicators",
        ),
        # Rename fields on Months
        migrations.RenameField(
            model_name="months",
            old_name="name",
            new_name="month_name",
        ),
        migrations.RenameField(
            model_name="months",
            old_name="image_key",
            new_name="month_image",
        ),
        # Add boolean status shadow
        migrations.AddField(
            model_name="months",
            name="status_bool",
            field=models.BooleanField(default=True),
        ),
        # Data migration to map status -> status_bool
        migrations.RunSQL(
            sql=(
                "UPDATE services_months SET status_bool = CASE WHEN status='active' THEN TRUE ELSE FALSE END"
            ),
            reverse_sql=(
                "UPDATE services_months SET status = CASE WHEN status_bool THEN 'active' ELSE 'deleted' END"
            ),
        ),
        # Remove old status and rename new one
        migrations.RemoveField(
            model_name="months",
            name="status",
        ),
        migrations.RenameField(
            model_name="months",
            old_name="status_bool",
            new_name="status",
        ),
        # Rename primary key id -> month_id
        migrations.RenameField(
            model_name="months",
            old_name="id",
            new_name="month_id",
        ),
    ]
